### ISSUE TITLE
test.py: remove unnecessary whitespaces

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#13]
There are some unnecessary empty lines starting from [line 16](https://github.com/DevoLearn/devolearn/blob/8570d92febf14c023d75e0b9d9028616e6832278/devolearn/tests/test.py#L16) to line 19 in [test.py](https://github.com/DevoLearn/devolearn/blob/master/devolearn/tests/test.py)

**Comment by Joel-hanson** [comment]
I would like to do this @Mayukhdeb

**Comment by Mayukhdeb** [comment]
Hello and welcome to devolearn! Feel free to make a pull request :)
