### ISSUE TITLE
__init__.py: reformat __all__

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#14]
The list [`__all__` ](https://github.com/DevoLearn/devolearn/blob/8570d92febf14c023d75e0b9d9028616e6832278/devolearn/__init__.py#L9 ) currently looks like:
```python
__all__ = ["lineage_populaton_model",
            "embryo_generator_model",
            "embryo_segmentor",
            "tests"]
```

But we want it to look like the one shown below:
```python
__all__ = [
    "lineage_populaton_model",
    "embryo_generator_model",
    "embryo_segmentor",
    "tests"
]
```

**Comment by jainal09** [comment]
Hi, hope this fixes this issue. @Mayukhdeb

**Comment by jainal09** [comment]
#21 format  __all__ in __init__.py
