### ISSUE TITLE
devolearn: add links to documentation in comments 

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#17]
Someone has to add link(s) to the [documentation](https://github.com/DevoLearn/devolearn#predicting-populations-of-cells-within-the-c-elegans-embryo) within the function comments. 

It is fine to add only one link to only one function to make a PR. We do not require for you to add all the links for all the functions. 

**Please see the example below:**

I'll be referring to [line 58](https://github.com/DevoLearn/devolearn/blob/8570d92febf14c023d75e0b9d9028616e6832278/devolearn/lineage_population_model/lineage_population_model.py#L58) in the [lineage_population_model.py](https://github.com/DevoLearn/devolearn/blob/master/devolearn/lineage_population_model/lineage_population_model.py)

The snippet there currently looks like this:
```python
    def predict(self, image_path):

        """
        input{
            image path <str>
        }
        output{
            dictionary containing the cell population values <dict>
        }
```

But we want somehting like: 

```python
    def predict(self, image_path):

        """
        reference{
            https://github.com/DevoLearn/devolearn#predicting-populations-of-cells-within-the-c-elegans-embryo
        } 
        input{
            image path <str>
        }
        output{
            dictionary containing the cell population values <dict>
        }
```

**Comment by rudrajit1729** [comment]
Can I be assigned to this?

**Comment by rudrajit1729** [comment]
@Mayukhdeb I can work on this. Please assign this to me. Thanks

**Comment by Mayukhdeb** [comment]
Thank you for your interest Rudrajit, we're loooking forward to your pull request :)

**Comment by rudrajit1729** [comment]
Do you need the same reference (https://github.com/DevoLearn/devolearn) across your codes. Please clear this @Mayukhdeb

**Comment by Mayukhdeb** [comment]
No, but you're almost right here:

We want you to add links to the respective documentation headings in the README.md file for the functions. Not just the link to the repository

The link that we'd want for the example shown above is:
```
https://github.com/DevoLearn/devolearn#predicting-populations-of-cells-within-the-c-elegans-embryo
```

And not:
```
https://github.com/DevoLearn/devolearn
```

Notice the `#readme-heading` in the end of the link.

**Comment by rudrajit1729** [comment]
ok got it. thanks

**Comment by rudrajit1729** [comment]
Done and submitted for review #19 Please review and merge if it satisfies the problem statement.

**Comment by rudrajit1729** [comment]
@Mayukhdeb
