### ISSUE TITLE
setup.py: change description

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#18]
The [current description](https://github.com/DevoLearn/devolearn/blob/8570d92febf14c023d75e0b9d9028616e6832278/setup.py#L11) on line 11 looks like:

```python
description="Accelerate data driven research on embryos with deep learning models",
```

But we want it to be like: 
```python
description="Accelerate data driven research in developmental biology with deep learning models",
```

**Comment by RaviKarrii** [comment]
I Would like to do this

**Comment by Mayukhdeb** [comment]
Hello and welcome to devolearn! We're looking forward to a pull request :)

**Comment by suparna13** [comment]
@Mayukhdeb I would like to contribute to this issue. Please assign it to me. Thanks.

**Comment by Mayukhdeb** [comment]
Thank you for your interest @suparna13, I would like you to look at the [contributing.md](https://github.com/DevoLearn/devolearn/blob/master/.github/contributing.md#git-commit-messages) file, and check the norms that we use for a proper commit message. 

Looking forward to a pull request :)
