### ISSUE TITLE
Add Hacktoberfest Topic

### ISSUE THREAD

**Issue by rudrajit1729** [DevoLearn/devolearn#24]
@Mayukhdeb please add hacktoberfest topic to the repo in order to make this repo eligible for hacktober fest 2020.
Here are the updated rules: https://hacktoberfest.digitalocean.com/hacktoberfest-update
To validate PRs after October 3, 2020 this topic must be included in repository.

**Comment by rudrajit1729** [comment]
All PRs submitted in and after October 3, 2020 will count as invalid unless "hacktoberfest" topic is added to the repo. Please look into this matter and add this minor change to validate successful PRs. @Mayukhdeb

**Comment by Mayukhdeb** [comment]
Thank you so much for letting us know ! I'll be adding the topic right away :)
