### ISSUE TITLE
setup: installation on colab initiates reinstallation of PyTorch

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#42]
Devolearn was written with Pytorch 1.7.0. but it might as well work on most of the more the other Pytorch versions (like the one on colab). If that is true, then we might not need this long reinstallation on google colab every time we do `pip install devolearn`

**Comment by vrutikrabadia** [comment]
Hi, Mayukh I am interested to work on this issue. First I will change the requirements version for PyTorch in the project and check breaking dependencies. If you have any more suggestions, it would be great with your guidance.

**Comment by Mayukhdeb** [comment]
Hi @vrutikrabadia, thanks for your interest. Feel free to make a PR if you solved it. Currently google colab is moving to pytorch `1.8` so try to check it devolearn works on that version or not. 

We might also have to completely refactor the `requirements.txt` file accordingly.

**Comment by vrutikrabadia** [comment]
I guess it is solved just checking all function for breaking dependencies

**Comment by vrutikrabadia** [comment]
Just to inform I found an issue in the sample notebook which needs to be updated.

**Comment by Mayukhdeb** [comment]
@vrutikrabadia please raise another issue and elaborate on it there
