### ISSUE TITLE
Try to integrate streamlit

### ISSUE THREAD

**Issue by Mayukhdeb** [DevoLearn/devolearn#58]
[Streamlit](https://github.com/streamlit/streamlit) seems to be an amazing option for deploying python backends with a clean GUI. We should definitely explore possibilities of building a GUI with streamlit for devolearn

**Comment by Mainakdeb** [comment]
Streamlit seems like a good option to deploy DevoLearn models via GUI. Will look into it soon 👍🏻

**Comment by Mayukhdeb** [comment]
devolearn is now available as a streamlit app on [heroku](https://devolearn.herokuapp.com/), so I guess we can close this issue 🙂
