### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by Mainakdeb** [DevoLearn/devolearn#61]
DevoLearn should migrate to [Github Actions](https://github.com/features/actions) because building on [travis-ci.org](https://travis-ci.org/) has ceased since June 15th, 2021.

**Comment by Mayukhdeb** [comment]
Fixed in a2a7279dab0fc81124d652d7d0016f47dcfd6cf3, thanks to @kingjuno
