### ISSUE TITLE
The embryo_segmentor_model folder is missing from the devolearn directory

### ISSUE THREAD

**Issue by Harikrishna-AL** [DevoLearn/devolearn#78]

**Comment by sushmanthreddy** [comment]
hey @Harikrishna-AL can u give little bit information about this issue?
actually [https://github.com/DevoLearn/devolearn/issues/69#issuecomment-1216505672](url) here in this issue channel it was clearly mentioned ,embryo_segmentor is no longer a function that is used in the newer versions of devolearn and it's name has been changed to something else.

may be this clears the issue right?

**Comment by Harikrishna-AL** [comment]
I wasn't aware that this problem was brought up in an another issue. Also, you said that the embryo_segmentor model was renamed to something else. So, Can you please point out which one that is? @sushmanthreddy

**Comment by sushmanthreddy** [comment]
@Harikrishna-AL  it has been renamed to cell_membrane_segmentor ...I hope u can close this issue now!

**Comment by Harikrishna-AL** [comment]
yeah thank you, I'll close it now.
